version: '3'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ORG=nwafu
      - DOCKER_INFLUXDB_INIT_BUCKET=k6-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=Wu8eHV8pEsm6vSaT9i8pobvOz7isGtRbccBbUxdTL374b7C5eYE8EFlfokzsURw4QDOePEIuuf5jdCTsoZQhxg==
    volumes:
      - influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:
